### ISSUE TITLE
Not able to convert VGG_F model with this

### ISSUE THREAD

**Issue by adityapatadia** [MarcBS/keras#5]
https://gist.github.com/ksimonyan/a32c9063ec8e1118221a#file-readme-md

I am not able to convert this model with this file. It gives me following error. `Layer weight shape (6400, 4096) not compatible with provided weight shape (9216, 4096).`

If I change input_dim to 227, everything works fine but I am skeptical if it will generate true conversion. Any ideas?

**Comment by darxriggs** [comment]
I think, I hit the same problem.

According to the referenced .prototxt file this is a V1 Caffe model (old).
V1 uses "layers" instead of "layer" as in V2.
The converter can handle that.

BUT
V1 also uses the property "input" instead of a layer of type "Data".
The converter cannot handle that as far as I can see.
I was using the config file from here http://www.robots.ox.ac.uk/~vgg/research/very_deep/ and got this error:
_Exception: Unknown node/input identifier: conv1_1_
